replace promises with async/await in ./pages
jenkoian/hacktoberfest-checker pull request #586
Opened 2021-10-02 02:31 UTC by GeoBrodas

Hi @jenkoian !

This is a great project, and a little complex for me as well, so I didn't touch anything in the `./api` folder. I have replaced the promises I saw in the `hooks` folder. All you need to do now is check! Hope it works! ( fingers crossed )

2021-10-02 09:32 UTC, jenkoian requested changes
Thanks for having a go at this, few comments 👍

2021-10-02 09:32 UTC, jenkoian commented on src/pages/User/components/PullRequests/hooks/useFetchPullRequests.js
> +//   }).then((response) => response.json());
Just remove all this, don't worry about leaving it in commented out.

2021-10-02 09:32 UTC, jenkoian commented on src/pages/User/components/PullRequests/hooks/useFetchPullRequests.js
> +// Code by Georgey
Can you remove? You can add your name to https://github.com/jenkoian/hacktoberfest-checker/blob/master/public/humans.txt if you want additional credit.

2021-10-02 09:32 UTC, jenkoian commented on src/pages/User/components/PullRequests/hooks/useFetchPullRequests.js
> +    //   );
Just remove all this, as above.

2021-10-02 09:32 UTC, jenkoian commented on src/pages/User/components/PullRequests/hooks/useFetchPullRequests.js
> +    const response = await fetchPullRequests(username);
This errors, it needs to be inside an async function. Can you take another look?

2021-10-02 09:32 UTC, jenkoian commented on src/pages/User/components/PullRequests/hooks/useFetchPullRequests.js
> +    if(errors) {
Think we're missing a space in here, you should be able to run `npm run prettier-fix` to correct 👍

2021-10-02 12:33 UTC, GeoBrodas commented
Hi @jenkoian ! Did everything as requested! Found this on how to use `async` inside a `useEffect`, and that's how I implemented it.
https://stackoverflow.com/questions/56838392/how-to-call-an-async-function-inside-a-useeffect-in-react

2021-10-02 13:55 UTC, jenkoian commented
Thanks @GeoBrodas I'm getting errors when I run it locally, are you able to take a look?

2021-10-02 16:59 UTC, GeoBrodas commented
Can you check now?

2021-10-02 17:30 UTC, jenkoian commented
@GeoBrodas same result I'm afraid

2021-10-03 14:23 UTC, GeoBrodas commented
> @GeoBrodas same result I'm afraid

I'll try to work on it! Typical case, never encountered this.

2022-09-30 14:41 UTC, closed without merging